# tavis.yml

language: node_js
node_js:
  - "7"

branches:
  only:
  - master
  - develop

before_script:
  - npm install -g --silent @angular/cli
  - npm install -g --silent firebase-tools
  - npm install

#script:
#  - if [ "$TRAVIS_BRANCH" == "master" ]; then ng build --prod; fi
#  - if [ "$TRAVIS_BRANCH" != "master" ]; then ng build --dev; fi
script:
  - ng build --prod

deploy:
  - provider: script
    script: scripts/deploy.sh develop
    on:
      branch: develop
  - provider: script
    script: scripts/deploy.sh production
    on:
      branch: master

notifications:
  slack: wefaves:F04bQ8KHvdkQJ5HtOUvhBvy8
