#.travis.yml

language: node_js
node_js:
  - "6.9.1"

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --dev

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  slack: wefaves:F04bQ8KHvdkQJ5HtOUvhBvy8
