#.travis.yml

language: node_js
node_js:
  - "6.9"

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod

after_success:
  - chmod +x deploy.sh
  - ./deploy.sh
